// ===== Flutter 3.35.x =====
// PdfHelper — generates and exports Business Analytics reports (PDF)

import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'package:flutter/foundation.dart' show kIsWeb;

// If you have the BusinessAnalytics entity, import it:
import 'package:hobby_sphere/features/activities/business/BusinessAnalytics/domain/entities/business_analytics.dart';

class PdfHelper {
  /// Build the PDF document with a clean table layout
  static Future<Uint8List> buildPdf(
    BusinessAnalytics analytics,
    int businessId,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (pw.Context ctx) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              "Business Analytics Report",
              style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
            ),
          ),

          pw.Paragraph(
            text:
                "Business ID: $businessId\n\n"
                "This report summarizes key business metrics "
                "including revenue, bookings, and performance.",
          ),
          pw.SizedBox(height: 16),

          // Metrics table
          pw.Table.fromTextArray(
            headers: ["Metric", "Value"],
            data: [
              ["Total Revenue", analytics.totalRevenue.toString()],
              ["Total Bookings", analytics.bookingGrowth.toString()],
              ["Active Items", analytics.topActivity.toString()],
              ["Peak Hours", analytics.peakHours.toString()],
              ["Customer Retention", "0%"], // Placeholder
              [
                "Report Date",
                DateTime.now().toIso8601String().split('T').first,
              ],
            ],
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 12,
            ),
            cellStyle: const pw.TextStyle(fontSize: 11),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellAlignment: pw.Alignment.centerLeft,
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(1),
            },
          ),

          pw.SizedBox(height: 20),

          pw.Text(
            "Generated by HobbySphere",
            style: pw.TextStyle(
              fontStyle: pw.FontStyle.italic,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  /// Open system print/save/share dialog (mobile: Android/iOS)
  static Future<void> showPrintDialog(
    BusinessAnalytics analytics,
    int businessId,
  ) async {
    final bytes = await buildPdf(analytics, businessId);
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => bytes,
      name: "business_analytics_report.pdf",
    );
  }

  /// Direct download / share (Web)
  static Future<void> downloadPdf(
    BusinessAnalytics analytics,
    int businessId,
  ) async {
    final bytes = await buildPdf(analytics, businessId);
    await Printing.sharePdf(
      bytes: bytes,
      filename: "business_analytics_report.pdf",
    );
    // OR, if you prefer a direct download dialog instead of share:
    // await Printing.downloadPdf(bytes: bytes, filename: "business_analytics_report.pdf");
  }

  /// Smart export (chooses mobile vs web automatically)
  static Future<void> exportPdf(
    BusinessAnalytics analytics,
    int businessId,
  ) async {
    if (kIsWeb) {
      await downloadPdf(analytics, businessId);
    } else {
      await showPrintDialog(analytics, businessId);
    }
  }
}
